### ISSUE TITLE
Feature Request - Behat tests

### ISSUE THREAD

**Issue by mchaneycamuk** [dthies/moodle-atto_fullscreen#10]
Are there any plans to support Behat tests for this Atto plugin? (in the same way that they are supported here: https://github.com/moodle/moodle/tree/master/lib/editor/atto/plugins/bold/tests/behat
Thanks
Mark

**Comment by dthies** [comment]
I thought about this in this past, but I am not sure what to test for. The bold button actually changes text. This button only changes the way it appears on the screen and whether it is correct is still subjective.

**Comment by dthies** [comment]
@mchaneycamuk Actually I suppose that it would be possible for me to at least check the button highlighting and that it continues to be highlighted correctly when html button is active.

**Comment by dthies** [comment]
I realized some useful test after fixing another issue with this plugin. If you can think of more useful tests, I would be happy to add them.

**Comment by markchaneyuk** [comment]
Thanks dthies. I cannot think of anything at the moment, unless there is a way to test that it actually does expand to full screen? Could you do a test to establish the previous size of the area before the button was clicked, then test it after the button has been clicked and do a delta to establish if it has increased?

**Comment by dthies** [comment]
It actually work just to check whether you can see other elements of the page that are suppose to be covered. So I added test to check whether country field is visible. I also added test of config setting so it should be complete.
