### ISSUE TITLE
Overlapping fullscreen modes

### ISSUE THREAD

**Issue by brian-winstead** [dthies/moodle-atto_fullscreen#11]
When creating a page resource it is possible to open the full screen mode of the Atto editor for two text fields, description and page content, at the same time.  After expanding to the full screen view for the description field, the user may use the tab key to have the page content field displayed overtop of the Atto fullscreen for the description field.  From there, the user may also expand the editor to full screen for the page content field.  The user may toggle off full screen for the page content field, to return to the fullscreen of the description field.  However, once full screen is closed for the page content field, other page elements not previously displayed are loaded over top of the full screen editor for the description field.  When using the Boost theme the navigation drawer is now loaded.  In the classic theme, any left-aligned blocks are now loaded.  The elements may obscure part or all of the description text as well as most of the Atto editor tool including the full screen toggle.  Ultimately, it is possible with enough scrolling or by collapsing the Boost navigation drawer to gain access to the full screen toggle control to exit the full screen mode for the description field, but the experience can be quite confusing to the user.  

I am not sure if the problem should be viewed as the nested full screen modes should not be permitted or that other page elements should not be loaded when toggling off fullscreen.

Here is a narrated video to help demonstrate the issue: https://www.screencast.com/t/ugnZNtkj.

STEPS TO REPLICATE
1. In a course using the Boost theme, turn editing on.
2. Expand the navigation drawer (top left button) if collapsed.
3. Click "Add an activity or resource" and choose the page resource.
4. Enter a name for the page.
5. Enter some text in the Description field.
6. Use the show/hide advanced buttons button on the Atto editor to expand all of the Atto editor tools.  
6. Click the Toggle full screen button for the description field.  Observe that the full screen mode of the Atto editor is opened blocking all other page elements including the navigation drawer.
7. Hit tab on the keyboard.  The Page content field is loaded over the middle of the fullscreen mode for the description field.  Enter some text in the page content field.
8. Use the show/hide advanced buttons button on the Atto editor to expand all of the Atto editor tools for the page content field.
9. Click the Toggle full screen button for the page content field.  Observe that only the Atto full screen mode for the page content field is displayed on the screen.
10. Click the Toggle full screen button again.
11. Observe that the you are returned to a view with the regular sized page content field displayed over top of the full screen mode for the description field.  However the boost navigation drawer is now also displayed over top of the full screen mode obscuring the Atto editor tools, including the full screen toggle.

NOTE: The same replication steps may be applied to the Classic theme which will result in the left-aligned blocks being loaded over top of the full screen Atto editor.

**Comment by dthies** [comment]
Hi Bryan,

Thanks for reporting this. I am sorry I have not addressed it yet. I would assume that it would be good to check whether the editor looses focus. If the one tabs off the editor it could go back to the regular size.

**Comment by dthies** [comment]
Bryan,

I have am updated version here now that checks whether focus appears somewhere outside the editor and collapses back to normal if that happens. So hitting the tab effective deactivates the button so there can be at most one fullscreen editor. I will copy it to the database in a few days.
