### ISSUE TITLE
syntax error, unexpected '.1' (T_DNUMBER) !!!

### ISSUE THREAD

**Issue by AdrianoRuseler** [dthies/moodle-atto_fullscreen#12]
Upgrading Moodle Core started...
!!! Exceção - syntax error, unexpected '.1' (T_DNUMBER) !!!

**Comment by dthies** [comment]
@AdrianoRuseler I just saw that and did a forced update this morning. Sorry about that.

**Comment by dthies** [comment]
@AdrianoRuseler I fixed a bug last night. Please, let me know if you still have an issue.

**Comment by AdrianoRuseler** [comment]
Thanks! It's working fine now!
