### ISSUE TITLE
Seeing an "echo" of the scroll bar on Google Chrome

### ISSUE THREAD

**Issue by balutz** [dthies/moodle-atto_fullscreen#3]
Hello, 

This issue might be more on Google's end? But when using the fullscreen plugin, I get an "echo" of the scroll bar appears over top of the hyperlink button, as shown below:

![screen shot 2015-09-14 at 2 38 12 pm](https://cloud.githubusercontent.com/assets/14282365/9861103/f5e360f2-5af5-11e5-8809-9bc30dd7533f.png)

This happens only after you have saved your text at least once using the Atto editor, and on all activities and resources; however, I have not observed this same behavior in FireFox or Safari, which renders this normally. It is unknown to me if it happens with MS Explorer.

Moodle version: 2.8.7
Theme: Essential

Thankya kindly.

**Comment by dthies** [comment]
Hello,
I have not been able to reproduce this myself.  Problems have appeared in certain themes before which were fixed by adding something to CSS. However, it is odd that it is Chrome specific.
Does this seem to appear everywhere or on a specific Moodle page? It might help to check the javascript console in case there is an error appearing there.

**Comment by balutz** [comment]
Hi, Daniel--

Thank you so much for your reply. It was indeed a problem with the CSS, and
I was able to write a rule to fix the problem.

The plugin works well for our purposes, and we appreciate the support.

Best,


On Fri, Sep 18, 2015 at 12:20 PM, Daniel Thies <notifications@github.com>
wrote:

> Hello,
> I have not been able to reproduce this myself. Problems have appeared in
> certain themes before which were fixed by adding something to CSS. However,
> it is odd that it is Chrome specific.
> Does this seem to appear everywhere or on a specific Moodle page? It might
> help to check the javascript console in case there is an error appearing
> there.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dthies/moodle-atto_fullscreen/issues/3#issuecomment-141512322>
> .
>



-- 
-- 

*Bryan A. Lutz*
Ph.D. Student | Teaching Associate | Moodle Administrator
Iowa State University |  balutz@iastate.edu

**Comment by dthies** [comment]
Hello Bryan,

If you don't mind sharing the rule that you used, I will include it in a future release. Essential is an important theme, and it would be great if it works out of the box.

Thanks,

Daniel
