### ISSUE TITLE
button conflicts with html+ plugin

### ISSUE THREAD

**Issue by bwl21** [dthies/moodle-atto_fullscreen#4]
I have installed both plugins, atto_fullscreen and atto_htmlplus.  In source mode - fullscreen toolbar button  is inactive.

**Comment by dthies** [comment]
Thanks for reporting this. I have a potential fix above.  Beside reactivating the button, I  added some code to resize the htmlplus display dynamically so that it will approximate the other window sizes. It will need some more  testing before I integrate it for a release.
