### ISSUE TITLE
Issues with Boost Theme

### ISSUE THREAD

**Issue by cmartintlh** [dthies/moodle-atto_fullscreen#8]
When utilizing Atto Fullscreen in conjunction with Atto HTML Plus on Boost theme, a col 3 pushes the content to the right and text extends off of the screen.

![screenshot 2017-04-19 17 28 55](https://cloud.githubusercontent.com/assets/26548100/25674428/c6a1c09c-3008-11e7-84ab-c20bed7f0864.png)

**Comment by abias** [comment]
As another user of these two plugins, I can confirm this problem.

**Comment by dthies** [comment]
Hi gentlemen, 
Thanks for reporting this. I think I have a fix now. Please, let me know whether it works with your setup.

**Comment by abias** [comment]
Hi Daniel,

I can confirm that your patch fixes the problem for me (tested in Chrome). I would be grateful if you could publish the fixes version in the Moodle plugins repo.

Thanks,
Alex

**Comment by dthies** [comment]
Thanks Alex,
I will update the database and close this issue.
